# -*- mode: ruby -*-
# vi: set ft=ruby :

# Require the AWS provider plugin and YAML module
require 'vagrant-aws'
require 'yaml'

# Read YAML file with instance information
instances = YAML.load_file(File.join(File.dirname(__FILE__), 'instances.yml'))['vm information']

# Specify Vagrant version and Vagrant API version
Vagrant.require_version '>= 1.6.0'
VAGRANTFILE_API_VERSION = '2'
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'aws'

# Create and configure the AWS instance(s)
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Function that sets up an aws VM
  def aws_vm(instance, yaml)
    # Disable default shared folder
    instance.vm.synced_folder '.', '/vagrant', disabled: true
  
    # Set per-instance provider configuration/overrides
    instance.vm.provider 'aws' do |aws, override|
      override.ssh.private_key_path = yaml['keyfile']
      override.ssh.username = yaml['user']
      aws.instance_type = yaml['type']
      aws.ami = yaml['ami']
      aws.region = yaml['region']
      aws.security_groups = yaml['security-groups']
      aws.tags = {'Name': yaml['name']}
    end # instance.vm.provider 'aws'
  end

  # Use dummy AWS box
  config.vm.box = 'aws-dummy'

  # Configure default AWS provider settings
  config.vm.provider 'aws' do |aws|

    # Specify default AWS key pair
    aws.keypair_name = 'Selenium'
  end # config.vm.provider 'aws'

  config.vm.define "node" do |node|
    aws_vm(node, instances["node"])
    config.vm.provision "file", source: "provision/get_selenium_url.py", destination: "get_selenium_url.py"
    config.vm.provision "file", source: "configuration/selenium_node.conf", destination: "selenium_node.conf"
    config.vm.provision "file", source: "configuration/xvfb.conf", destination: "xvfb.conf"
    config.vm.provision "file", source: "configuration/x11vnc.conf", destination: "x11vnc.conf"
    config.vm.provision "shell", path: "provision/move_files.sh"
    config.vm.provision "shell", path: "provision/selenium.sh", args: ENV['HUB_SERVER']
    config.vm.provision "shell", path: "provision/chrome.sh"
    config.vm.provision "shell", path: "provision/xvfb.sh"
  end

  config.vm.define "hub" do |hub|
    aws_vm(hub, instances["hub"])
    config.vm.provision "file", source: "provision/get_selenium_url.py", destination: "get_selenium_url.py"
    config.vm.provision "file", source: "configuration/selenium_hub.conf", destination: "selenium_hub.conf"
    config.vm.provision "shell", path: "provision/move_files.sh"
    config.vm.provision "shell", path: "provision/selenium.sh"
  end

  config.vm.define "standalone" do |standalone|
    aws_vm(standalone, instances["standalone"])
    config.vm.provision "file", source: "provision/get_selenium_url.py", destination: "get_selenium_url.py"
    config.vm.provision "file", source: "configuration/selenium_standalone.conf", destination: "selenium_standalone.conf"
    config.vm.provision "file", source: "configuration/xvfb.conf", destination: "xvfb.conf"
    config.vm.provision "file", source: "configuration/x11vnc.conf", destination: "x11vnc.conf"
    config.vm.provision "shell", path: "provision/move_files.sh"
    config.vm.provision "shell", path: "provision/selenium.sh"
    config.vm.provision "shell", path: "provision/chrome.sh"
    config.vm.provision "shell", path: "provision/xvfb.sh"
  end
end # Vagrant.configure
