# -*- mode: ruby -*-
# vi: set ft=ruby :

# Require the AWS provider plugin and YAML module
require 'vagrant-aws'
require 'yaml'

# Read YAML file with instance information
instances = YAML.load_file(File.join(File.dirname(__FILE__), 'instances.yml'))

# Specify Vagrant version and Vagrant API version
Vagrant.require_version '>= 1.6.0'
VAGRANTFILE_API_VERSION = '2'
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'aws'

# Create and configure the AWS instance(s)
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Use dummy AWS box
  config.vm.box = 'aws-dummy'

  # Configure default AWS provider settings
  config.vm.provider 'aws' do |aws|

    # Specify default AWS key pair
    aws.keypair_name = 'Selenium'
  end # config.vm.provider 'aws'

  # Loop through YAML file and set per-instance information
  instances.each do |instance|
    config.vm.define instance['name'] do |srv|

      # Disable default shared folder
      srv.vm.synced_folder '.', '/vagrant', disabled: true

      # Set per-instance provider configuration/overrides
      srv.vm.provider 'aws' do |aws, override|
        override.ssh.private_key_path = instance['keyfile']
        override.ssh.username = instance['user']
        aws.instance_type = instance['type']
        aws.ami = instance['ami']
	aws.region = instance['region']
        aws.security_groups = instance['security-groups']
	aws.tags = {'Name': instance['name']}
      end # srv.vm.provider 'aws'
    end # config.vm.define
  end # instances.each
end # Vagrant.configure
